// Generated by gencpp from file poly_ros/obstacle.msg
// DO NOT EDIT!


#ifndef POLY_ROS_MESSAGE_OBSTACLE_H
#define POLY_ROS_MESSAGE_OBSTACLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace poly_ros
{
template <class ContainerAllocator>
struct obstacle_
{
  typedef obstacle_<ContainerAllocator> Type;

  obstacle_()
    : nomer(0)
    , angle1(0.0)
    , angle2(0.0)
    , min_distance(0.0)  {
    }
  obstacle_(const ContainerAllocator& _alloc)
    : nomer(0)
    , angle1(0.0)
    , angle2(0.0)
    , min_distance(0.0)  {
    }



   typedef uint8_t _nomer_type;
  _nomer_type nomer;

   typedef float _angle1_type;
  _angle1_type angle1;

   typedef float _angle2_type;
  _angle2_type angle2;

   typedef float _min_distance_type;
  _min_distance_type min_distance;




  typedef boost::shared_ptr< ::poly_ros::obstacle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::poly_ros::obstacle_<ContainerAllocator> const> ConstPtr;

}; // struct obstacle_

typedef ::poly_ros::obstacle_<std::allocator<void> > obstacle;

typedef boost::shared_ptr< ::poly_ros::obstacle > obstaclePtr;
typedef boost::shared_ptr< ::poly_ros::obstacle const> obstacleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::poly_ros::obstacle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::poly_ros::obstacle_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace poly_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'poly_ros': ['/home/ubuntu/catkin_ws/src/poly_ros/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::poly_ros::obstacle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::poly_ros::obstacle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::poly_ros::obstacle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::poly_ros::obstacle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::poly_ros::obstacle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::poly_ros::obstacle_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::poly_ros::obstacle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "955dce79f36c78247816cb38f3fca159";
  }

  static const char* value(const ::poly_ros::obstacle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x955dce79f36c7824ULL;
  static const uint64_t static_value2 = 0x7816cb38f3fca159ULL;
};

template<class ContainerAllocator>
struct DataType< ::poly_ros::obstacle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "poly_ros/obstacle";
  }

  static const char* value(const ::poly_ros::obstacle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::poly_ros::obstacle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 nomer\n\
float32 angle1\n\
float32 angle2\n\
float32 min_distance\n\
\n\
\n\
\n\
";
  }

  static const char* value(const ::poly_ros::obstacle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::poly_ros::obstacle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.nomer);
      stream.next(m.angle1);
      stream.next(m.angle2);
      stream.next(m.min_distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct obstacle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::poly_ros::obstacle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::poly_ros::obstacle_<ContainerAllocator>& v)
  {
    s << indent << "nomer: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.nomer);
    s << indent << "angle1: ";
    Printer<float>::stream(s, indent + "  ", v.angle1);
    s << indent << "angle2: ";
    Printer<float>::stream(s, indent + "  ", v.angle2);
    s << indent << "min_distance: ";
    Printer<float>::stream(s, indent + "  ", v.min_distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POLY_ROS_MESSAGE_OBSTACLE_H
