// Generated by gencpp from file poly_ros/obstacles.msg
// DO NOT EDIT!


#ifndef POLY_ROS_MESSAGE_OBSTACLES_H
#define POLY_ROS_MESSAGE_OBSTACLES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <poly_ros/obstacle.h>

namespace poly_ros
{
template <class ContainerAllocator>
struct obstacles_
{
  typedef obstacles_<ContainerAllocator> Type;

  obstacles_()
    : num(0)
    , mass()  {
    }
  obstacles_(const ContainerAllocator& _alloc)
    : num(0)
    , mass(_alloc)  {
    }



   typedef int32_t _num_type;
  _num_type num;

   typedef std::vector< ::poly_ros::obstacle_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::poly_ros::obstacle_<ContainerAllocator> >::other >  _mass_type;
  _mass_type mass;




  typedef boost::shared_ptr< ::poly_ros::obstacles_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::poly_ros::obstacles_<ContainerAllocator> const> ConstPtr;

}; // struct obstacles_

typedef ::poly_ros::obstacles_<std::allocator<void> > obstacles;

typedef boost::shared_ptr< ::poly_ros::obstacles > obstaclesPtr;
typedef boost::shared_ptr< ::poly_ros::obstacles const> obstaclesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::poly_ros::obstacles_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::poly_ros::obstacles_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace poly_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'poly_ros': ['/home/ubuntu/catkin_ws/src/poly_ros/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::poly_ros::obstacles_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::poly_ros::obstacles_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::poly_ros::obstacles_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::poly_ros::obstacles_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::poly_ros::obstacles_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::poly_ros::obstacles_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::poly_ros::obstacles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8355408b6d63bfa55a44fef1ba63e6aa";
  }

  static const char* value(const ::poly_ros::obstacles_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8355408b6d63bfa5ULL;
  static const uint64_t static_value2 = 0x5a44fef1ba63e6aaULL;
};

template<class ContainerAllocator>
struct DataType< ::poly_ros::obstacles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "poly_ros/obstacles";
  }

  static const char* value(const ::poly_ros::obstacles_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::poly_ros::obstacles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 num\n\
poly_ros/obstacle[] mass\n\
\n\
================================================================================\n\
MSG: poly_ros/obstacle\n\
uint8 nomer\n\
float32 angle1\n\
float32 angle2\n\
float32 min_distance\n\
\n\
\n\
\n\
";
  }

  static const char* value(const ::poly_ros::obstacles_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::poly_ros::obstacles_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num);
      stream.next(m.mass);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct obstacles_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::poly_ros::obstacles_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::poly_ros::obstacles_<ContainerAllocator>& v)
  {
    s << indent << "num: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num);
    s << indent << "mass[]" << std::endl;
    for (size_t i = 0; i < v.mass.size(); ++i)
    {
      s << indent << "  mass[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::poly_ros::obstacle_<ContainerAllocator> >::stream(s, indent + "    ", v.mass[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // POLY_ROS_MESSAGE_OBSTACLES_H
